from collections.abc import Iterable

def prompt(questions: list[Question]) -> dict[str, str] | None: ...

class Question: ...

class List(Question):
    def __init__(self, name: str, message: str, choices: Iterable[str]) -> None: ...
